### PR TITLE
MAINT: Fix example notebooks

### PR DESCRIPTION
**Pull request by arm61**
Fixing the included example Jupyter notebooks to be compatible with most recent updates in the code

### CODE REVIEW

**Comment by andyfaff** [comment]
Not sure if I can merge this PR as is because reflectometry_analysis also touched by #95. Do I have to merge one, then the other? Alternatively, could you add the changes from #95 to this PR?

**Comment by arm61** [comment]
I have realised that I messed up the pull requests, this one has all the changes that I made. I will close #95 and this one can be merged on its own

**Comment by andyfaff** [comment]
Did you check that they run without problems? If so, then they can go in.

**Comment by arm61** [comment]
Yup all seem to run without issue

**Comment by andyfaff** [comment]
Going to merge, after squashing.

**Pull request merged**
