### PR TITLE
ENH: reversed structure

### PR DESCRIPTION
**Pull request by andyfaff**
add `reversed` attribute to `refnx.reflect.Structure`. This enables you to calculate the front/back reflectivity from the same structure very easily.

### CODE REVIEW

**Comment by andyfaff** [comment]
@igresh - comments?

**Comment by igresh** [comment]
I can see no problems with the implementation. This change will make using refnx for a series of related fits in a notebook much cleaner.

There is an argument to be made that this feature should be  accessed through the model rather than the structure (as its technically not a structural change, but a change to the experimental setup) - but if this should happen it can happen later on.

**Comment by andyfaff** [comment]
Can you think of a better name than reversed?

**Comment by igresh** [comment]
If it's accessed through structure reversed makes good sense. 

If it's accessed through model then something like Neutron_Incidence = "Back" or "Bottom" / "Front" or "Top" would make sense (you loose the Boolean, but it's more readable IMO).

**Comment by andyfaff** [comment]
I did it through Structure because Structure also calculates the sld
profile.

**Comment by igresh** [comment]
It's current implementation makes sense (and I'm happy with it) but it could be implemented in any class with access to the slabs (I think).

**Pull request merged**
